/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 The sidebars can be generated from the filesystem, or explicitly defined here.
 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  bittensorSidebar: [
    // 	{
    // 	type: 'link',
    // 	href: 'https://docs.bittensor.com',
    // 	label: "Search",
    // 	className: 'sidebarSearch', //  based on Class name it will add search component
    // },
    "index",
    {
      type: "category",
      label: "Understand Bittensor",
      link: {type: "doc", id: "learn/introduction"},
      collapsible: true,
      collapsed: true,
      items: [
        "learn/introduction",
        "questions-and-answers",
        "subnets/understanding-subnets", 
        "learn/bittensor-building-blocks",
        "learn/anatomy-of-incentive-mechanism",
        "emissions",
        "yuma-consensus",        
      ],
    },
        {
      type: "category",
      label: "Dynamic TAO",
      link: {type: "doc", id: "dynamic-tao/index",},
      collapsible: true,
      collapsed: true,
      items: [
      "dynamic-tao/dtao-guide",
      "dynamic-tao/dtao-faq",
      "dynamic-tao/sdk-cheat-sheet",
      
      ],
    },

    {
      type: "category",
      label: "Staking/Delegation",
      collapsible: true,
      collapsed: true,
      link: {type: "doc", id: "staking-and-delegation/delegation",},
      items: [
      "staking-and-delegation/delegation",
      "dynamic-tao/staking-unstaking-dtao",
      "staking-and-delegation/managing-stake-btcli",
      "staking-and-delegation/managing-stake-sdk",
      "staking-and-delegation/staking-polkadot-js",
      "staking-and-delegation/using-ledger-hw-wallet"],
    },
    {
      type: "category",
      label: "Mining",
      collapsible: true,
      collapsed: true,
      link: {type: "doc", id: "miners/index",},
      items: [
      "miners/index",
      // "miners/miners-guide-wallets-keys"
      ],
    },

    {
      type: "category",
      label: "Validating",
      collapsible: true,
      collapsed: true,
      link: {type: "doc", id: "validators/index",},
      items: [
      "validators/index",
              "subnets/child-hotkeys",
      ],
    },
    {
      type: "category",
      label: "Managing subnets",      
      collapsible: true,
      collapsed: true,
      items: [
        "subnets/create-a-subnet",
        "subnets/subnet-hyperparameters",
        "subnets/working-with-subnets",
        "subnets/walkthrough-prompting",
        "tutorials/basic-subnet-tutorials",
        "tutorials/ocr-subnet-tutorial",
      ],
    },
        {
      type: "category",
      label: "Tools and Special Features",
      link: {type: "doc", id: "tools",},
      collapsible: true,
      collapsed: true,
      items: [
        "bittensor-networks",
        "subnets/commit-reveal",
        "subnets/consensus-based-weights",
        "subnets/schedule-coldkey-swap",
        "subnets/asyncio",
          "subnets/bt-logging-levels",        
        "utilities",
      ],
    },
        {
          type: "category",
          label: "BTCLI: The Bittensor CLI",
          collapsible: true,
          collapsed: true,
          items: [
            "getting-started/install-btcli",
            "btcli",
          ]
        },
        {
          type: "category",
          label: "Bittensor Python SDK",
          collapsible: true,
          collapsed: true,
          items: [
            "getting-started/installation",
            "bt-api-ref",    
            "getting-started/install-wallet-sdk",        
            "migration_guide",
          ]
        },        
        
        {
          type: "category",
          label: "Wallets and Keys",
          collapsible: true,
          collapsed: true,
          items: [
            "getting-started/wallets",
            "working-with-keys",
            // "keys-questions",
          ]
        },
{
      type: "category",
      label: "Subtensor Nodes",
      link: {type: "doc", id: "subtensor-nodes/index",},
      collapsible: true,
      collapsed: true,
      items: [
        "subtensor-nodes/subtensor-node-requirements",
        "subtensor-nodes/using-source",
        "subtensor-nodes/using-docker",
        "subtensor-nodes/subtensor-rate-limits",
        "subtensor-nodes/subtensor-storage-query-examples",
        "subtensor-nodes/subtensor-error-messages",
      ],
    },
    
    {
      type: "category",
      label: "EVM smart contracts on Bittensor",
      link: {type: "doc", id: "evm-tutorials/index",},
      collapsible: true,
      collapsed: true,
      items: [
        "evm-tutorials/evm-on-subtensor",
        "evm-tutorials/install",
        "evm-tutorials/evm-testnet-with-metamask-wallet",
        "evm-tutorials/evm-localnet-with-metamask-wallet",
        "evm-tutorials/evm-mainnet-with-metamask-wallet",
        "evm-tutorials/transfer-from-metamask-to-ss58",
        "evm-tutorials/transfer-between-two-h160-accounts",
        "evm-tutorials/hardhat-config-for-subtensor-evm",
        "evm-tutorials/staking-precompile",
        "evm-tutorials/ed25519-verify-precompile",
      ],
    },
    {
      type: "category",
      label: "Governance",
      collapsible: true,
      collapsed: true,
      items: [
      "governance",
      "senate",
      ],
    },
    {
      type: "category",
      label: "Release Notes and Updates",
      collapsible: true,
      collapsed: true,
      items: [
        "chain-rel-notes",
        "bittensor-rel-notes",
      ],
    },

    "errors-and-troubleshooting",
    "media-assets",
    "glossary",

  ],
};

module.exports = sidebars;
