/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Bittensor",
  "tagline": "Developer Documentation",
  "favicon": "img/favicon.ico",
  "url": "https://docs.bittensor.com",
  "baseUrl": "/",
  "organizationName": "opentensor",
  "projectName": "new-docs",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "throw",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "routeBasePath": "/",
          "path": "docs",
          "remarkPlugins": [
            null
          ],
          "rehypePlugins": [
            null
          ],
          "sidebarPath": "/Users/rajkaramchedu/Opentensor/new-docs/sidebars.js",
          "sidebarCollapsible": true,
          "showLastUpdateTime": true
        },
        "theme": {
          "customCss": "/Users/rajkaramchedu/Opentensor/new-docs/src/css/custom.css"
        }
      }
    ]
  ],
  "stylesheets": [
    {
      "href": "https://cdn.jsdelivr.net/npm/katex@0.13.24/dist/katex.min.css",
      "type": "text/css",
      "integrity": "sha384-odtC+0UGzzFL/6PNoE8rX/SPcQDXBJ+uRepguP4QkPCm2LBxH3FA3y+fKSiJ+AmM",
      "crossorigin": "anonymous"
    }
  ],
  "themeConfig": {
    "image": "img/docusaurus-social-card.jpg",
    "docs": {
      "sidebar": {
        "autoCollapseCategories": true,
        "hideable": false
      },
      "versionPersistence": "localStorage"
    },
    "navbar": {
      "title": "Developer Documentation",
      "logo": {
        "alt": "Bittensor",
        "src": "img/logo.svg",
        "srcDark": "img/logo-dark-mode.svg"
      },
      "items": [
        {
          "position": "left",
          "label": "Bittensor API Reference",
          "href": "pathname:///python-api/html/index.html"
        },
        {
          "href": "https://wallet.bittensor.com/",
          "label": "Wallet",
          "position": "right"
        },
        {
          "href": "https://github.com/opentensor/new-docs",
          "label": "GitHub",
          "position": "right"
        },
        {
          "href": "https://bittensor.com/about",
          "label": "About Bittensor",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "bash",
        "diff",
        "json"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "algolia": {
      "appId": "B07G29NY9F",
      "apiKey": "d23c920e8a9bdae899572be3c8494696",
      "indexName": "bittensor-docs",
      "contextualSearch": true,
      "insights": true,
      "debug": false,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "footer": {
      "links": [
        {
          "title": "Wallet",
          "items": [
            {
              "label": "Bittensor Wallet",
              "to": "https://wallet.bittensor.com/"
            }
          ]
        },
        {
          "title": "About",
          "items": [
            {
              "label": "About Bittensor",
              "to": "https://bittensor.com/about"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Bittensor Discord",
              "href": "https://discord.gg/qasY3HA9F9"
            },
            {
              "label": "Documentation GitHub",
              "href": "https://github.com/opentensor/new-docs"
            }
          ]
        }
      ],
      "copyright": "© 2023 <a href=\"https://bittensor.com\">Bittensor</a> • Opentensor Foundation",
      "style": "light"
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    }
  }
};
